# Generated by Django 2.1.7 on 2019-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_no', models.CharField(max_length=9)),
                ('a_type', models.CharField(max_length=5)),
                ('a_from', models.CharField(max_length=3)),
                ('a_time', models.CharField(max_length=5)),
                ('d_to', models.CharField(max_length=3)),
                ('d_time', models.CharField(max_length=5)),
            ],
        ),
    ]
